version: '3.8'

services:

  db-telecom:
    image: postgres:15-alpine
    restart: always
    container_name: db-ctrlbee
    environment:
      - 'POSTGRES_USER=telecom'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_DB=telecom'
    ports:
      - "127.0.0.1:5432:5432"
    expose:
      - "5432"
    command: -p 5432
    volumes:
      - db-telecom:/var/lib/postgresql/data


  web-app:
    container_name: web-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
volumes:
  db-telecom: